# While technically this is using hugo-nederburg, the theme has been extensibly
# modified, and rarely with an eye towards re-use.  If you try to use it, don't
# be surprised to find ugly stuff hardcoded.

theme = "hugo-nederburg"

baseURL = "/"
title = "Brodie Gaslam"
languageCode = "en-us"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]

# Enable comments by entering your Disqus shortname
disqusShortname = ""

# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

preserveTaxonomyNames = true
paginate = 7           # frontpage pagination
summaryLength = 10     # num words in summary

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    title = "Brodie Gaslam"  # needed for use with $.Params "title"
    websiteURL = "https://www.brodieg.com"
    mainSections = ["post"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"#

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"  

    # Unmark to use post folder for images. Default is static folder.
    #usepostimgfolder = true

    slogan = "An #rstats Blog, Mostly."
    description = "An #rstats Blog, Mostly." # meta description
    contenttype = "website"

    # You need to set author to have an author bio. If you have a writer in the
    # markdown file it will override this.

    author = "Brodie Gaslam"
    twitterhandle  = "@brodiegaslam"
    authorLink = "https://www.brodieg.com/about/"
    bio = [
      "Brodie Gaslam is a hobbyist programmer based on the US East Coast."
    ]
    copyright = [
      "Copyright &copy; Brodie Gaslam"
    ]
    image = "/images/moon-small.png"

    # Contact page
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below (it is also used in Gravatar
    #   for the bio).  
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # email = "goran@molnsys.com"

  # Nav links in the side bar
  # [[menu.main]]
  # name = "Home"
  # url = "/"
  # weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  # [[menu.main]]
  # name = "Get in touch"
  # url = "contact/"
  # weight = 3

  [params.logo]
  url = "/images/moon-small.png"
  width = 40
  height = 40
  alt = "Logo"

  # this will also be in author bio if there is no writer.

  [params.social]
  # facebook      = "full Social profile url in facebook"
  # googleplus    = "full profile url in googleplus"
  # email         = "email@example.com"
  twitter       = "https://twitter.com/BrodieGaslam"
  mastodon      = "https://mastodon.social/@brodieg"
  # linkedin      = "full profile url in linkedin"
  stackoverflow = "https://stackoverflow.com/users/2725969/brodieg"
  # instagram     = "full profile url in instagram"
  github        = "https://github.com/brodieG/"
  # pinterest     = "full profile url in pinterest"
  rss           = true

  # Add a writer, then use it in the markdown front matter like this: 
  #   writer = "Lukas Herman"

  [params.writers]
    [params.writers."Brodie Gaslam"]

    link = "https://www.brodieg.com/about/"
    bio = [
       "Brodie Gaslam is a hobbyist programmer based on the US East Coast."
     ]
    mastodon      = "https://mastodon.social/@brodieg"
     twitter       = "https://twitter.com/BrodieGaslam"
     stackoverflow = "https://stackoverflow.com/users/2725969/brodieg"
     github        = "https://github.com/brodieG/"
